---
title: "STA 210: Regression Analysis"
tbl-colwidths: [5,10,40,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester.
Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
|           Week            | Date        | Topic                                         |             Prepare              |                   Slides                   |                            AE                            |                                                                      Lab                                                                       |                                                           HW                                                            |           Exam           |             Project             |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
|  [1](/weeks/week-1.html)  | Wed, Jan 5  | Lab 0 - Meet + greet                          |                                  |   [🖥️](/slides/lab-0.html "Lab slides")    |                                                          |                                                   [💻](/labs/lab-0.html "Lab instructions")                                                    |                                                                                                                         |                          |                                 |
|                           | Thu, Jan 6  | Welcome to STA 210!                           | [📖](/weeks/week-1.html#prepare) | [🖥️](/slides/lec-1.html "Lecture slides")  |    [📋](/ae/ae-0-movies.html "Application exercise")     |                                                                                                                                                |                                                                                                                         |                          |                                 |
|  [2](/weeks/week-2.html)  | Mon, Jan 10 | Lab 1 - Meet the toolkit                      |                                  |   [🖥️](/slides/lab-1.html "Lab slides")    |                                                          |                                                   [💻](/labs/lab-1.html "Lab instructions")                                                    |                                                                                                                         |                          |                                 |
|                           | Tue, Jan 11 | Simple linear regression (SLR)                | [📖](/weeks/week-2.html#prepare) | [🖥️](/slides/lec-2.html "Lecture slides")  |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Jan 13 | SLR: Model fitting in R with tidymodels       |                                  | [🖥️](/slides/lec-3.html "Lecture slides")  |  [📋](/ae/ae-1-dcbikeshare.html "Application exercise")  |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Jan 14 | Released: HW 5                                |                                  |                                            |                                                          |                                                                                                                                                |                                                   [✍️](/hw/hw-5.html)                                                   |                          |                                 |
|                           |             | Due: Lab 1                                    |                                  |                                            |                                                          | [💻](/labs/lab-1.html "Lab instructions") [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-1-key.pdf) |                                                                                                                         |                          |                                 |
|  [3](/weeks/week-3.html)  | Mon, Jan 17 | *Martin Luther King, Jr. Day*                 |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Jan 18 | SLR: Prediction + model evaluation            | [📖](/weeks/week-3.html#prepare) | [🖥️](/slides/lec-4.html "Lecture slides")  |  [📋](/ae/ae-2-dcbikeshare.html "Application exercise")  |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Jan 20 | SLR: Simulation-based inference               |                                  |   [🖥️](/slides/lec-5.html "Lab slides")    |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Jan 21 | Released: HW 1                                |                                  |                                            |                                                          |                                                                                                                                                |                                                   [✍️](/hw/hw-1.html)                                                   |                          |                                 |
|  [4](/weeks/week-4.html)  | Mon, Jan 24 | Lab 2 - College scorecard                     |                                  |    [🖥️](/slides/lab-2.pdf "Lab slides")    |                                                          |                                                   [💻](/labs/lab-2.html "Lab instructions")                                                    |                                                                                                                         |                          |                                 |
|                           | Tue, Jan 25 | SLR: Mathematical models for inference        | [📖](/weeks/week-4.html#prepare) | [🖥️](/slides/lec-6.html "Lecture slides")  |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Jan 27 | SLR: Model diagnostics                        |                                  | [🖥️](/slides/lec-7.html "Lecture slides")  |  [📋](/ae/ae-3-duke-forest.html "Application exercise")  |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Jan 28 | Due: HW 1 + Lab 2                             |                                  |                                            |                                                          | [💻](/labs/lab-2.html "Lab instructions") [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-2-key.pdf) | [✍️](/hw/hw-1.html) [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-1-key.pdf) |                          |                                 |
|  [5](/weeks/week-5.html)  | Mon, Jan 31 | Lab 3 - Coffee ratings                        |                                  |   [🖥️](/slides/lab-3.html "Lab slides")    |                                                          | [💻](/labs/lab-3.html "Lab instructions") [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-3-key.pdf) |                                                                                                                         |                          |                                 |
|                           | Tue, Feb 1  | Multiple linear regression (MLR)              | [📖](/weeks/week-5.html#prepare) | [🖥️](/slides/lec-8.html "Lecture slides")  |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Feb 3  | Exam 1 review                                 |                                  | [🖥️](/slides/lec-9.html "Lecture slides")  | [📋](/ae/ae-4-exam-1-review.html "Application exercise") |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Feb 4  | Released: Exam 1                              |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         | [✅](/exams/exam-1.html) |                                 |
|                           |             | Due: Lab 3                                    |                                  |                                            |                                                          |                                                   [💻](/labs/lab-3.html "Lab instructions")                                                    |                                                                                                                         |                          |                                 |
|  [6](/weeks/week-6.html)  | Mon, Feb 7  | No lab: Work on Exam 1                        |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: Exam 1                                   |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         | [✅](/exams/exam-1.html) |                                 |
|                           | Tue, Feb 8  | MLR: Types of predictors                      | [📖](/weeks/week-6.html#prepare) | [🖥️](/slides/lec-10.html "Lecture slides") |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Feb 10 | MLR: Model comparison                         |                                  | [🖥️](/slides/lec-11.html "Lecture slides") |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Feb 11 | Released: HW 2                                |                                  |                                            |                                                          |                                                                                                                                                |                                                   [✍️](/hw/hw-2.html)                                                   |                          |                                 |
|  [7](/weeks/week-7.html)  | Mon, Feb 14 | Lab: Project topic ideas                      |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          | [📂](/project-description.html) |
|                           | Tue, Feb 15 | MLR: Feature engineering                      | [📖](/weeks/week-7.html#prepare) | [🖥️](/slides/lec-12.html "Lecture slides") |  [📋](/ae/ae-5-the-office.html "Application exercise")   |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Feb 17 | MLR: Feature engineering                      |                                  | [🖥️](/slides/lec-13.html "Lecture slides") |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Feb 18 | Due: HW 2 + Project topic ideas               |                                  |                                            |                                                          |                                                                                                                                                | [✍️](/hw/hw-2.html) [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/hw-2-key.pdf) |                          | [📂](/project-description.html) |
|  [8](/weeks/week-8.html)  | Mon, Feb 21 | Lab 4: The Office                             |                                  |                                            |                                                          |                                                   [💻](/labs/lab-4.html "Lab instructions")                                                    |                                                                                                                         |                          |                                 |
|                           | Tue, Feb 22 | MLR: Cross validation                         | [📖](/weeks/week-8.html#prepare) | [🖥️](/slides/lec-14.html "Lecture slides") | [📋](/ae/ae-6-the-office-cv.html "Application exercise") |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Feb 24 | Exam 2 review                                 |                                  | [🖥️](/slides/lec-15.html "Lecture slides") | [📋](/ae/ae-7-exam-2-review.html "Application exercise") |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Feb 25 | Released: Exam 2                              |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         | [✅](/exams/exam-2.html) |                                 |
|                           |             | Due: Lab 4                                    |                                  |                                            |                                                          | [💻](/labs/lab-4.html "Lab instructions") [🗝️](https://sakai.duke.edu/access/content/group/779c3ebe-3b88-4bcc-bd01-1813e8396a23/lab-4-key.pdf) |                                                                                                                         |                          |                                 |
|  [9](/weeks/week-9.html)  | Mon, Feb 28 | No lab: Work on Exam 2                        |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: Exam 2                                   |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         | [✅](/exams/exam-2.html) |                                 |
|                           | Tue, Mar 1  | MLR: Inference                                | [📖](/weeks/week-9.html#prepare) | [🖥️](/slides/lec-16.html "Lecture slides") |  [📋](/ae/ae-8-rail-trail.html "Application exercise")   |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Mar 3  | MLR: Inference conditions + multicollinearity |                                  | [🖥️](/slides/lec-17.html "Lecture slides") |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Mon, Mar 7  | *Spring break*                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Mar 8  | *Spring break*                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Mar 10 | *Spring break*                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [10](/weeks/week-10.html) | Mon, Mar 14 | Lab: Work on project proposals                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Mar 15 | Logistic regression (LR)                      |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Mar 17 | Probabilities, odds, and odds ratios          |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Mar 18 | Due: Project proposals                        |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Released: HW 3                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [11](/weeks/week-11.html) | Mon, Mar 21 | Lab 6: TBA                                    |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Mar 22 | LR: Prediction / classification               |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Mar 24 | LR: Model validation                          |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Mar 25 | Released: HW 4                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: HW3 + Lab 6                              |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [12](/weeks/week-12.html) | Mon, Mar 28 | Lab 7: TBA                                    |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Mar 29 | LR: Inference + conditions                    |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Mar 31 | Multinomial Logistic Regression (MultiLR)     |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Apr 1  | Released: HW 4                                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: Lab 7                                    |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [13](/weeks/week-13.html) | Mon, Apr 4  | Lab: Work on project drafts                   |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Apr 5  | MultiLR: Prediction                           |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Apr 7  | TBA                                           |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Apr 8  | Due: HW 4 + Project drafts                    |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [14](/weeks/week-14.html) | Mon, Apr 11 | Lab: Project peer review of drafts            |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Apr 12 | Work on project                               |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Apr 14 | Exam 3 review                                 |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Fri, Apr 15 | Released: Exam 3                              |                                  |                                            |                                                          |                                                                                                                                                |                                                   [✍️](/hw/hw-5.html)                                                   |                          |                                 |
|                           |             | Due: Peer review                              |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [15](/weeks/week-15.html) | Mon, Apr 18 | No lab: Work on Exam 3                        |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: Exam 3                                   |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Tue, Apr 18 | Wrap-up                                       |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           |             | Due: HW 5                                     |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
| [16](/weeks/week-16.html) | Mon, Apr 25 | Due: Project write-up                         |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Thu, Apr 28 | Due: Video presentation + repo                |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
|                           | Sat, Apr 30 | Due: Video comments                           |                                  |                                            |                                                          |                                                                                                                                                |                                                                                                                         |                          |                                 |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
