---
title: "Week 4"
subtitle: "TBA"
editor: visual
---

::: callout-important
If you can't be in class for the lectures, you can watch the live stream or watch the recording later on [Panopto](https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx#folderID=%22d6c1d58a-cb6d-4732-9d4b-ae0c011bf767%22).
:::

To be posted.

## Prepare

Due: Jan 24

All required prepare activities are due **by the beginning of class (1:45 pm)** on the specified date.

📖 Read Introduction to Modern Statistics, Sec 24.4: [Mathematical model for testing the slope](https://openintro-ims.netlify.app/inf-model-slr.html#mathslope)

📖 Read Introduction to Modern Statistics, Sec 24.5: [Mathematical model, interval for the slope](https://openintro-ims.netlify.app/inf-model-slr.html#mathematical-model-interval-for-the-slope)

📖 Read Introduction to Modern Statistics, Sec 24.6: [Checking model conditions](https://openintro-ims.netlify.app/inf-model-slr.html#tech-cond-linmod)

📖 Read Introduction to Modern Statistics, Sec 24.7: [Chapter review](https://openintro-ims.netlify.app/inf-model-slr.html#chp24-review)

## Participate

🖥️ Lecture 6 - SLR: Mathematical models for inference (to be posted)

🖥️ Lecture 7 - SLR: Model diagnostic (to be posted)

## Perform

⌨️ [Lab 2 - College scorecard](/labs/lab-2.html "Lab instructions")

✍️ [HW 1 - In-person voting trends](/hw/hw-1.html)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
