---
title: "Exam 1 Review"
subtitle: "STA 210 - Spring 2022"
author: "Dr. Mine Çetinkaya-Rundel"
footer: "[sta210-s22.github.io/website](https://sta210-s22.github.io/website/)"
logo: "images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: true
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
editor: visual
execute:
  freeze: auto
---

## Announcements

-   Lab 3 due tomorrow (Friday) at 5pm on Gradescope, one submission per team
-   Exam 1 open tomorrow (Friday) at 9am and ends on Monday, Feb 7 at 11:59pm
-   No lab on Monday, take the time to work on your exam

## Feedback from submissions so far

-   You must submit a PDF (not HTML) to Gradescope
-   You must tag your pages when you upload to Gradescope -- if you don't know how to do this, please ask well before the deadline!
-   You must not refer to keys distributed in previous semesters of the course -- much of what we're doing is different and some of it is the same. If you need help, please ask!

## Exam 1

-   Instructions can be found at
-   Covers everything we've done so far
-   Office hours:
    -   Tomorrow's TA office hours are *only* for Lab 3 questions

    -   Monday: I have office hours 10:30-11:30am
-   Any clarification questions for the exam?
    -   Direct message me or Rick on Slack

    -   Post on Sakai Conversations, post to "Instructors in this site"

## Application Exercise

::: appex
📋 [github.com/sta210-s22/ae-4-exam-1-review](https://github.com/sta210-s22/?q=ae-4-exam-1-review&type=all&language=&sort=)
:::
