---
title: "Exam 3 review"
subtitle: "STA 210 - Spring 2022"
author: "Dr. Mine Çetinkaya-Rundel"
footer: "[sta210-s22.github.io/website](https://sta210-s22.github.io/website/)"
logo: "images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    transition: fade
    slide-number: true
    incremental: true 
    chalkboard: true
    highlight-style: ayu-mirage
code-link: true
editor: visual
execute:
  freeze: auto
  echo: true
---

```{r}
#| include: false

# figure options
knitr::opts_chunk$set(
  fig.width = 8, fig.asp = 0.618, out.width = "90%",
  fig.retina = 3, dpi = 300, fig.align = "center"
)

library(countdown)
```

## Exam instructions {.smaller}

-   The exam is an individual assignment.
    Everything in your repository is for your eyes only.

-   You may not collaborate or communicate anything about this exam to anyone except the instructor.
    For example, you may not communicate with other students, the TAs, or post/solicit help on the internet, email or via any other method of communication.

-   The exam is open-book, open-note, so you may use any materials from class as you take the exam.

-   No TA office hours will be held during the exam.
    You may not email the TAs questions about the exam.

-   If you have questions, email or Slack me.

## Exam coverage and format

-   Focuses on content Weeks 09 - 14, but can include material from previous weeks

-   Similar format as previous exams

    -   Part 1: Multiple choice/fill-in-the-blank questions on Sakai
    -   Part 2: Open-ended data analysis in GitHub and submitted on Gradescope

## Part 2 of the exam

-   **Goal:** Assess your understanding of the course material and how the methods you learned are applied to the analysis of real-world data.

-   Include all of your analysis steps in your exam write up, unless stated otherwise.

    -   For example, if the exam says "assume conditions are met," You can reference that information in your write up but don't have to recheck the conditions.

## Assessment criteria {.smaller}

-   You can identify the correct approach, analysis method, and/or inferential results required to answer the question.
-   You understand the correct conditions and diagnostics needed to determine whether the conclusions drawn from the model will be reliable
-   You can write results and conclusions in a meaningful way that can be understood by a general audience (think a business or research partner)
-   You can produce a report that is suitable for a professional audience (e.g., narrative is written in complete sentences, all graphs have proper titles and axis labels, there is not extraneous output, all Latex is rendered)
-   You can conduct the analysis using a reproducible data analysis workflow that incorporates version control

## Application exercise

::: appex
📋 [github.com/sta210-s22/ae-12-exam-3-review](https://github.com/sta210-s22/ae-12-exam-3-review/search?q=ae-12-exam-3-review)
:::
