{
  "hash": "d4c88b7e0186a3a5633827ba95e086c9",
  "result": {
    "markdown": "---\ntitle: \"SLR: Simulation based-inference\"\nsubtitle: \"STA 210 - Spring 2022\"\nauthor: \"Dr. Mine Çetinkaya-Rundel\"\nfooter:  \"[sta210-s22.github.io/website](https://sta210-s22.github.io/website/)\"\nlogo: \"images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: true\n    transition: fade\n    slide-number: true\n    incremental: true \neditor: visual\nexecute:\n  freeze: auto\n---\n\n\n\n# Welcome\n\n## Announcements\n\n-   HW 1 posted tomorrow, due next Friday\n\n## Computational setup\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)   # for data wrangling and visualization\nlibrary(tidymodels)  # for modeling\nlibrary(usdata)      # for the county_2019 dataset\nlibrary(openintro)   # for the duke_forest dataset\nlibrary(scales)      # for pretty axis labels\nlibrary(glue)        # for constructing character strings\nlibrary(knitr)       # for pretty tables\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n# Recap of last lecture\n\n## Terminology\n\n-   Outcome: y\n-   Predictor: x\n-   Observed y, $y$: truth\n-   Predicted y, $\\hat{y}$: fitted, estimated\n-   Residual: difference between observed and predicted outcome for a given value of predictor\n\n## Model evaluation {.smaller}\n\n-   One concern in evaluating models is how well they do for prediction\n-   We're generally interested in how well a model might do for predicting the outcome for a new observation, not for predicting the outcome for an observation we used to fit the model (and already know its observed value)\n-   Evaluating predictive performance: Split the data into testing and training sets, build models using only the training set, and evaluate their performance on the testing set, and repeat many times to see how your model holds up to \"new\" data\n-   Quantifying variability of of estimates: Bootstrap the data, fit a model, obtain coefficient estimates and/or measures of strength of fit, and repeat many times to see how your model holds up to \"new\" data\n-   Today we introduced these concepts, throughout the semester we'll learn how to implement them (i.e., write the code) and how to interpret their results\n\n## Uninsurance vs. HS graduation in NC\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/nc-uninsured-hsgrad-scatter-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## Uninsurance vs. HS graduation in NY\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ncounty_2019_ny <- county_2019 %>%\n  as_tibble() %>%\n  filter(state == \"New York\") %>%\n  select(name, hs_grad, uninsured)\n\nggplot(county_2019_ny,\n       aes(x = hs_grad, y = uninsured)) +\n  geom_point() +\n  scale_x_continuous(labels = label_percent(scale = 1, accuracy = 1)) +\n  scale_y_continuous(labels = label_percent(scale = 1, accuracy = 1)) +\n  labs(\n    x = \"High school graduate\", y = \"Uninsured\",\n    title = \"Uninsurance vs. HS graduation rates\",\n    subtitle = \"New York counties, 2015 - 2019\"\n  ) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"pink\")\n```\n\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/ny-uninsured-hsgrad-scatter-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## Data splitting\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-1-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## Bootstrapping\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## Comparing NY and NC\n\n::: question\nWhy are the fits from the NY models more variable than those from the NC models?\n:::\n\n# Statistical inference\n\n## Data: Sale prices of houses in Duke Forest\n\n::: columns\n::: {.column width=\"50%\"}\n-   Data on houses that were sold in the Duke Forest neighborhood of Durham, NC around November 2020\n-   Scraped from Zillow\n-   Source: [`openintro::duke_forest`](http://openintrostat.github.io/openintro/reference/duke_forest.html)\n:::\n\n::: {.column width=\"50%\"}\n![](images/lec-5/duke_forest_home.jpg){fig-alt=\"Home in Duke Forest\" fig-align=\"center\" width=\"400\"}\n:::\n:::\n\n## Exploratory analysis\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## Modeling {.smaller}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(price ~ area, data = duke_forest)\n\ntidy(df_fit) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n|term        |  estimate| std.error| statistic| p.value|\n|:-----------|---------:|---------:|---------:|-------:|\n|(Intercept) | 116652.33|  53302.46|      2.19|    0.03|\n|area        |    159.48|     18.17|      8.78|    0.00|\n:::\n:::\n\n. . .\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n-   **Intercept:** Duke Forest houses that are 0 square feet are expected to sell, on average, for $116,652.\n-   **Slope:** For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159.\n\n## Sample to population {.smaller}\n\n> For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159.\n\n-   This estimate is valid for the single sample of 98 houses.\n-   But what if we're not interested quantifying the relationship between the size and price of a house in this single sample?\n-   What if we want to say something about the relationship between these variables for all houses in Duke Forest?\n\n## Statistical inference\n\n-   Statistical inference allows provide methods and tools for us to use the single sample we have observed to make valid statements (inferences) about the population it comes from\n\n-   For our inferences to be valid, the sample should be random and representative of the population we're interested in\n\n## Inference for simple linear regression\n\n-   Calculate a confidence interval for the slope, $\\beta_1$\n\n-   Conduct a hypothesis test for the interval, $\\beta_1$\n\n# Confidence interval for the slope\n\n## Confidence interval {.smaller}\n\n-   A plausible range of values for a population parameter is called a **confidence interval**\n-   Using only a single point estimate is like fishing in a murky lake with a spear, and using a confidence interval is like fishing with a net\n    -   We can throw a spear where we saw a fish but we will probably miss, if we toss a net in that area, we have a good chance of catching the fish\n    -   Similarly, if we report a point estimate, we probably will not hit the exact population parameter, but if we report a range of plausible values we have a good shot at capturing the parameter\n\n## Confidence interval for the slope {.smaller}\n\nA confidence interval will allow us to make a statement like \"*For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, give or take X dollars.*\"\n\n-   Should X be \\$10?\n    \\$100?\n    \\$1000?\n\n-   If we were to take another sample of 98 would we expect the slope calculated based on that sample to be exactly $159?\n    Off by \\$10?\n    \\$100?\n    \\$1000?\n\n-   The answer depends on how variable (from one sample to another sample) the sample statistic (the slope) is\n\n-   We need a way to quantify the variability of the sample statistic\n\n## Quantify the variability of the slope {.smaller}\n\n**for estimation**\n\n-   Two approaches:\n    1.  Via simulation (what we'll do today)\n    2.  Via mathematical models (what we'll do in the next class)\n-   Bootstrapping to quantify the variability of the slope for the purpose of estimation:\n    -   Bootstrap new samples from the original sample\n    -   Fit models to each of the samples and estimate the slope\n    -   Use features of the distribution of the bootstrapped slopes to construct a confidence interval\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n## Bootstrap sample 1\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Bootstrap sample 2\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Bootstrap sample 3\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Bootstrap sample 4\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Bootstrap sample 5\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n. . .\n\n*so on and so forth...*\n\n## Bootstrap samples 1 - 5\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Bootstrap samples 1 - 100\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Slopes of bootstrap samples\n\n::: question\n**Fill in the blank:** For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, give or take \\_\\_\\_ dollars.\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## Slopes of bootstrap samples\n\n::: question\n**Fill in the blank:** For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $159, give or take \\_\\_\\_ dollars.\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-23-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## Confidence level\n\n::: question\nHow confident are you that the true slope is between \\$0 and \\$250?\nHow about \\$150 and \\$170?\nHow about \\$90 and \\$210?\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-24-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## 95% confidence interval\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=80%}\n:::\n:::\n\n-   A 95% confidence interval is bounded by the middle 95% of the bootstrap distribution\n-   We are 95% confident that For each additional square foot, the model predicts the sale price of Duke Forest houses to be higher, on average, by $90.43 to $205.77.\n\n## Computing the CI for the slope I\n\nCalculate the observed slope:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nobserved_fit <- duke_forest %>%\n  specify(price ~ area) %>%\n  fit()\n\nobserved_fit\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 2\n  term      estimate\n  <chr>        <dbl>\n1 intercept  116652.\n2 area          159.\n```\n:::\n:::\n\n## Computing the CI for the slope II {.smaller}\n\nTake `100` bootstrap samples and fit models to each one:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# #| code-line-numbers: \"1,5,6\"\n\nset.seed(1120)\n\nboot_fits <- duke_forest %>%\n  specify(price ~ area) %>%\n  generate(reps = 100, type = \"bootstrap\") %>%\n  fit()\n\nboot_fits\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 200 × 3\n# Groups:   replicate [100]\n   replicate term      estimate\n       <int> <chr>        <dbl>\n 1         1 intercept   47819.\n 2         1 area          191.\n 3         2 intercept  144645.\n 4         2 area          134.\n 5         3 intercept  114008.\n 6         3 area          161.\n 7         4 intercept  100639.\n 8         4 area          166.\n 9         5 intercept  215264.\n10         5 area          125.\n# … with 190 more rows\n```\n:::\n:::\n\n## Computing the CI for the slope III\n\n**Percentile method:** Compute the 95% CI as the middle 95% of the bootstrap distribution:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# #| code-line-numbers: \"5\"\n\nget_confidence_interval(\n  boot_fits, \n  point_estimate = observed_fit, \n  level = 0.95,\n  type = \"percentile\"\n)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          92.1     223.\n2 intercept -36765.   296528.\n```\n:::\n:::\n\n## Computing the CI for the slope IV\n\n**Standard error method:** Alternatively, compute the 95% CI as the point estimate $\\pm$ \\~2 standard deviations of the bootstrap distribution:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# #| code-line-numbers: \"5\"\n\nget_confidence_interval(\n  boot_fits, \n  point_estimate = observed_fit, \n  level = 0.95,\n  type = \"se\"\n)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          90.8     228.\n2 intercept -56788.   290093.\n```\n:::\n:::\n\n## Precision vs. accuracy\n\n::: question\nIf we want to be very certain that we capture the population parameter, should we use a wider or a narrower interval?\nWhat drawbacks are associated with using a wider interval?\n:::\n\n. . .\n\n![](images/lec-5/garfield.png){fig-alt=\"Garfield comic\" fig-align=\"center\" width=\"600\"}\n\n## Precision vs. accuracy\n\n::: question\nHow can we get best of both worlds -- high precision and high accuracy?\n:::\n\n## Changing confidence level\n\n::: question\nHow would you modify the following code to calculate a 90% confidence interval?\nHow would you modify it for a 99% confidence interval?\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# #| code-line-numbers: \"|4\"\n\nget_confidence_interval(\n  boot_fits, \n  point_estimate = observed_fit, \n  level = 0.95,\n  type = \"percentile\"\n)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          92.1     223.\n2 intercept -36765.   296528.\n```\n:::\n:::\n\n## Changing confidence level\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## confidence level: 90%\nget_confidence_interval(\n  boot_fits, point_estimate = observed_fit, \n  level = 0.90, type = \"percentile\"\n)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          104.     212.\n2 intercept  -24380.  256730.\n```\n:::\n\n```{.r .cell-code}\n## confidence level: 99%\nget_confidence_interval(\n  boot_fits, point_estimate = observed_fit, \n  level = 0.99, type = \"percentile\"\n)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term      lower_ci upper_ci\n  <chr>        <dbl>    <dbl>\n1 area          56.3     226.\n2 intercept -61950.   370395.\n```\n:::\n:::\n\n## Recap {.smaller}\n\n-   **Population:** Complete set of observations of whatever we are studying, e.g., people, tweets, photographs, etc. (population size = $N$)\n-   **Sample:** Subset of the population, ideally random and representative (sample size = $n$)\n-   Sample statistic $\\ne$ population parameter, but if the sample is good, it can be a good estimate\n-   **Statistical inference:** Discipline that concerns itself with the development of procedures, methods, and theorems that allow us to extract meaning and information from data that has been generated by stochastic (random) process\n-   We report the estimate with a confidence interval, and the width of this interval depends on the variability of sample statistics from different samples from the population\n-   Since we can't continue sampling from the population, we bootstrap from the one sample we have to estimate sampling variability\n\n## Sampling is natural {.smaller}\n\n![](images/lec-5/soup.png){fig-alt=\"Illustration of a bowl of soup\" fig-align=\"center\" width=\"300\"}\n\n-   When you taste a spoonful of soup and decide the spoonful you tasted isn't salty enough, that's exploratory analysis\n-   If you generalize and conclude that your entire soup needs salt, that's an inference\n-   For your inference to be valid, the spoonful you tasted (the sample) needs to be representative of the entire pot (the population)\n\n# Hypothesis test for the slope\n\n## Statistical significance\n\n::: columns\n::: {.column width=\"30%\"}\nDo the data provide sufficient evidence that $\\beta_1$ (the true slope for the population) is different from 0?\n:::\n\n::: {.column width=\"70%\"}\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-5_files/figure-revealjs/unnamed-chunk-32-1.png){fig-align='center' width=100%}\n:::\n:::\n:::\n:::\n\n## Hypotheses\n\n-   We want to answer the question \"Do the data provide sufficient evidence that $\\beta_1$ (the true slope for the population) is different from 0?\"\n-   **Null hypothesis** - $H_0: \\beta_1 = 0$, there is no linear relationship between `area` and `price`\n-   **Alternative hypothesis** - $H_A: \\beta_1 \\ne 0$, there is a linear relationship between `area` and `price`\n\n## Hypothesis testing as a court trial\n\n-   **Null hypothesis**, $H_0$: Defendant is innocent\n-   **Alternative hypothesis**, $H_A$: Defendant is guilty\n-   **Present the evidence:** Collect data\n-   **Judge the evidence:** \"Could these data plausibly have happened by chance if the null hypothesis were true?\"\n    -   Yes: Fail to reject $H_0$\n\n    -   No: Reject $H_0$\n\n## Hypothesis testing framework {.smaller}\n\n-   Start with a null hypothesis, $H_0$ that represents the status quo\n-   Set an alternative hypothesis, $H_A$ that represents the research question, i.e. what we're testing for\n-   Conduct a hypothesis test under the assumption that the null hypothesis is true and calculate a **p-value** (probability of observed or more extreme outcome given that the null hypothesis is true)\n    -   if the test results suggest that the data do not provide convincing evidence for the alternative hypothesis, stick with the null hypothesis\n    -   if they do, then reject the null hypothesis in favor of the alternative",
    "supporting": [
      "lec-5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    function fireSlideChanged(previousSlide, currentSlide) {\n\n      // dispatch for htmlwidgets\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for reveal\n    if (window.Reveal) {\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\n        fireSlideChanged(event.previousSlide, event.currentSlide);\n      });\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}