{
  "hash": "fe217dc8d079074901b6ae29a37e81e2",
  "result": {
    "markdown": "---\ntitle: \"Multiple linear regression (MLR)\"\nsubtitle: \"STA 210 - Spring 2022\"\nauthor: \"Dr. Mine Çetinkaya-Rundel\"\nfooter: \"[sta210-s22.github.io/website](https://sta210-s22.github.io/website/)\"\nlogo: \"images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: true\n    transition: fade\n    slide-number: true\n    incremental: true \n    chalkboard: true\neditor: visual\nexecute:\n  freeze: auto\n---\n\n\n\n# Welcome\n\n## Announcements {.smaller}\n\n-   Lab 3:\n\n    ::: nonincremental\n    -   Any questions about lab / teamwork?\n    -   Due Friday, Feb 4 at 5pm\n    :::\n\n-   Exam 1:\n\n    ::: nonincremental\n    -   Released Friday, Feb 4\n    -   Multiple choice questions (mostly conceptual) + open-ended exercises (like lab + homework)\n    -   Open book, open internet, open questions to me + Rick (head TA) only\n    -   No communication with others or posting questions on the internet allowed\n    -   What can you do to start preparing?\n        -   Review readings, assignments, feedback returned\n\n        -   Organize your notes\n\n        -   Come to office hours with questions\n    :::\n\n## Computational setup\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)   # for data wrangling and visualization\nlibrary(tidymodels)  # for modeling\nlibrary(openintro)   # for the duke_forest dataset\nlibrary(scales)      # for pretty axis labels\nlibrary(knitr)       # for pretty tables\nlibrary(patchwork)   # for laying out plots\nlibrary(GGally)      # for pairwise plots\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 20))\n```\n:::\n\n# Considering multiple variables\n\n## House prices in Levittown\n\n-   The data set contains the sales price and characteristics of 85 homes in Levittown, NY that sold between June 2010 and May 2011.\n-   Levittown was built right after WWII and was the first planned suburban community built using mass production techniques.\n-   The article [\"Levittown, the prototypical American suburb -- a history of cities in 50 buildings, day 25\"](https://www.theguardian.com/cities/2015/apr/28/levittown-america-prototypical-suburb-history-cities) gives an overview of Levittown's controversial history.\n\n## Analysis goals\n\n-   We would like to use the characteristics of a house to understand variability in the sales price.\n\n-   To do so, we will fit a **multiple linear regression model**.\n\n-   Using our model, we can answers questions such as\n\n    ::: nonincremental\n    -   What is the relationship between the characteristics of a house in Levittown and its sale price?\n    -   Given its characteristics, what is the expected sale price of a house in Levittown?\n    :::\n\n## The data {.smaller}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevittown <- read_csv(here::here(\"slides/data/homeprices.csv\"))\nlevittown\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 85 × 7\n   bedrooms bathrooms living_area lot_size year_built property_tax sale_price\n      <dbl>     <dbl>       <dbl>    <dbl>      <dbl>        <dbl>      <dbl>\n 1        4       1          1380     6000       1948         8360     350000\n 2        4       2          1761     7400       1951         5754     360000\n 3        4       2          1564     6000       1948         8982     350000\n 4        5       2          2904     9898       1949        11664     375000\n 5        5       2.5        1942     7788       1948         8120     370000\n 6        4       2          1830     6000       1948         8197     335000\n 7        4       1          1585     6000       1948         6223     295000\n 8        4       1           941     6800       1951         2448     250000\n 9        4       1.5        1481     6000       1948         9087     299990\n10        3       2          1630     5998       1948         9430     375000\n# … with 75 more rows\n```\n:::\n:::\n\n## Variables {.smaller}\n\n**Predictors**:\n\n::: nonincremental\n-   `bedrooms`: Number of bedrooms\n-   `bathrooms`: Number of bathrooms\n-   `living_area`: Total living area of the house (in square feet)\n-   `lot_size`: Total area of the lot (in square feet)\n-   `year_built`: Year the house was built\n-   `property_tax`: Annual property taxes (in USD)\n:::\n\n**Response:** `sale_price`: Sales price (in USD)\n\n## EDA: Response variable\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-9_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## EDA: Predictor variables\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-9_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## EDA: Response vs. Predictors\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-9_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n## EDA: All variables\n\n::: panel-tabset\n## Plot\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-9_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=80%}\n:::\n:::\n\n## Code\n\n::: {.cell layout-align=\"center\" hash='lec-9_cache/revealjs/levittown-pairs_1eda1c132dcc1e5c551b4551bfd818ee'}\n\n```{.r .cell-code  code-line-numbers=\"|1\"}\nggpairs(levittown) +\n  theme(\n    axis.text.y = element_text(size = 10),\n    axis.text.x = element_text(angle = 45, size = 10),\n    strip.text.y = element_text(angle = 0, hjust = 0)\n    )\n```\n:::\n:::\n\n## Single vs. multiple predictors\n\nSo far we've used a *single predictor variable* to understand variation in a quantitative response variable\n\n. . .\n\nNow we want to use *multiple predictor variables* to understand variation in a quantitative response variable\n\n# Multiple linear regression\n\n## Multiple linear regression (MLR) {.smaller}\n\nBased on the analysis goals, we will use a **multiple linear regression** model of the following form\n\n$$\n\\begin{aligned}\\hat{\\text{sale_price}} ~ = & ~\n\\hat{\\beta}_0 + \\hat{\\beta}_1 \\text{bedrooms} + \\hat{\\beta}_2 \\text{bathrooms} + \\hat{\\beta}_3 \\text{living_area} \\\\\n&+ \\hat{\\beta}_4 \\text{lot_size} + \\hat{\\beta}_5 \\text{year_built} + \\hat{\\beta}_6 \\text{property_tax}\\end{aligned}\n$$\n\nSimilar to simple linear regression, this model assumes that at each combination of the predictor variables, the values `sale_price` follow a Normal distribution.\n\n## Regression Model\n\n**Recall:** The simple linear regression model assumes\n\n$$\nY|X\\sim N(\\beta_0 + \\beta_1 X, \\sigma_{\\epsilon}^2)\n$$\n\n. . .\n\n**Similarly:** The multiple linear regression model assumes\n\n$$\nY|X_1, X_2, \\ldots, X_p \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p, \\sigma_{\\epsilon}^2)\n$$\n\n## The MLR model\n\nFor a given observation $(x_{i1}, x_{i2} \\ldots, x_{ip}, y_i)$\n\n$$\ny_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_p x_{ip} + \\epsilon_{i} \\hspace{8mm} \\epsilon_i \\sim N(0,\\sigma_\\epsilon^2)\n$$\n\n## Prediction\n\nAt any combination of the predictors, the mean value of the response $Y$, is\n\n$$\n\\mu_{Y|X_1, \\ldots, X_p} = \\beta_0 + \\beta_1 X_{1} + \\beta_2 X_2 + \\dots + \\beta_p X_p\n$$\n\n. . .\n\nUsing multiple linear regression, we can estimate the mean response for any combination of predictors\n\n$$\n\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_{1} + \\hat{\\beta}_2 X_2 + \\dots + \\hat{\\beta}_p X_{p}\n$$\n\n## Model fit {.smaller}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nprice_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(sale_price ~ bedrooms + bathrooms + living_area + lot_size +\n        year_built + property_tax, data = levittown)\n\ntidy(price_fit) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n|term         |     estimate|   std.error| statistic| p.value|\n|:------------|------------:|-----------:|---------:|-------:|\n|(Intercept)  | -7148818.957| 3820093.694|    -1.871|   0.065|\n|bedrooms     |   -12291.011|    9346.727|    -1.315|   0.192|\n|bathrooms    |    51699.236|   13094.170|     3.948|   0.000|\n|living_area  |       65.903|      15.979|     4.124|   0.000|\n|lot_size     |       -0.897|       4.194|    -0.214|   0.831|\n|year_built   |     3760.898|    1962.504|     1.916|   0.059|\n|property_tax |        1.476|       2.832|     0.521|   0.604|\n:::\n:::\n\n## Model equation\n\n$$\n\\begin{align}\\hat{\\text{price}} = & -7148818.957 - 12291.011 \\times \\text{bedrooms}\\\\[5pt]  \n&+ 51699.236 \\times \\text{bathrooms}  + 65.903 \\times \\text{living area}\\\\[5pt]\n&- 0.897 \\times \\text{lot size} +  3760.898 \\times \\text{year built}\\\\[5pt] \n&+ 1.476 \\times \\text{property tax}\n\\end{align}\n$$\n\n## Interpreting $\\hat{\\beta}_j$ {.smaller}\n\n-   The estimated coefficient $\\hat{\\beta}_j$ is the expected change in the mean of $y$ when $x_j$ increases by one unit, <i>holding the values of all other predictor variables constant</i>.\n\n. . .\n\n-   **Example:** The estimated coefficient for `living_area` is 65.90. This means for each additional square foot of living area, we expect the sale price of a house in Levittown, NY to increase by \\$65.90, on average, holding all other predictor variables constant.\n\n## Prediction {.smaller}\n\n::: question\nWhat is the predicted sale price for a house in Levittown, NY with 3 bedrooms, 1 bathroom, 1,050 square feet of living area, 6,000 square foot lot size, built in 1948 with \\$6,306 in property taxes?\n:::\n\n<br>\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n-7148818.957 - 12291.011 * 3 + 51699.236 * 1 + \n  65.903 * 1050 - 0.897 * 6000 + 3760.898 * 1948 + \n  1.476 * 6306\n```\n\n::: {.cell-output-stdout}\n```\n[1] 265360.4\n```\n:::\n:::\n\n. . .\n\nThe predicted sale price for a house in Levittown, NY with 3 bedrooms, 1 bathroom, 1050 square feet of living area, 6000 square foot lot size, built in 1948 with \\$6306 in property taxes is **\\$265,360**.\n\n## Prediction, revisit\n\nJust like with simple linear regression, we can use the `predict()` function in R to calculate the appropriate intervals for our predicted values:\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_house <- tibble(\n  bedrooms = 3, bathrooms = 1, \n  living_area = 1050, lot_size = 6000, \n  year_built = 1948, property_tax = 6306\n  )\n\npredict(price_fit, new_house)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 1 × 1\n    .pred\n    <dbl>\n1 265360.\n```\n:::\n:::\n\n## Confidence interval for $\\hat{\\mu}_y$\n\n::: question\nCalculate a 95% confidence interval for the **estimated mean price** of houses in Levittown, NY with 3 bedrooms, 1 bathroom, 1050 square feet of living area, 6000 square foot lot size, built in 1948 with \\$6306 in property taxes.\n:::\n\n<br>\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(price_fit, new_house, type = \"conf_int\", level = 0.95)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 1 × 2\n  .pred_lower .pred_upper\n        <dbl>       <dbl>\n1     238482.     292239.\n```\n:::\n:::\n\n## Prediction interval for $\\hat{y}$\n\n::: question\nCalculate a 95% prediction interval for an individual house in Levittown, NY with 3 bedrooms, 1 bathroom, 1050 square feet of living area, 6000 square foot lot size, built in 1948 with \\$6306 in property taxes.\n:::\n\n<br>\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(price_fit, new_house, type = \"pred_int\", level = 0.95)\n```\n\n::: {.cell-output-stdout}\n```\n# A tibble: 1 × 2\n  .pred_lower .pred_upper\n        <dbl>       <dbl>\n1     167277.     363444.\n```\n:::\n:::\n\n## Cautions\n\n-   **Do not extrapolate!** Because there are multiple predictor variables, there is the potential to extrapolate in many directions\n-   The multiple regression model only shows **association, not causality**\n    -   To show causality, you must have a carefully designed experiment or carefully account for confounding variables in an observational study\n\n## Recap\n\n::: nonincremental\n-   Introduced multiple linear regression\n\n-   Interpreted a coefficient $\\hat{\\beta}_j$\n\n-   Used the model to calculate predicted values and the corresponding intervals\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    function fireSlideChanged(previousSlide, currentSlide) {\n\n      // dispatch for htmlwidgets\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for reveal\n    if (window.Reveal) {\n      window.Reveal.addEventListener(\"slidechanged\", function(event) {\n        fireSlideChanged(event.previousSlide, event.currentSlide);\n      });\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}